### PR TITLE
Handle OG Pyroscope endpoints in query frontend

### LINKED ISSUE #2133: Parellize render queries
Currently the query frontend doesn't split by time and execute in parallel.

I see two solutions:
- Either we deprecate those render APIs.
- Or we use we push up in the frontend the render logic, which basically queries for SelectSeries and SelectMergeStacktraces in the frontend. Technically we should be able to use the same code.

cc @kolesnikovae

### PR DESCRIPTION
**Pull request by kolesnikovae**
Resolves #2133. The change allows to deprecate the [`querier.Diff`](https://github.com/grafana/pyroscope/blob/1596f8a119d74d9272a523444dbb2ff0f84cecf4/api/querier/v1/querier.proto#L16) method.

### CODE REVIEW

File: pkg/util/connectgrpc/connectgrpc.go [hunk 1]
```diff
@@ -115,17 +115,31 @@ func decodeRequest[Req any](req *httpgrpc.HTTPRequest) (*connect.Request[Req], e
...
 	// e.g. initial Content-Type could be 'application/json'.
 	h := removeContentHeaders(req.Header().Clone())
 	h.Set("Content-Type", "application/proto")
 	out := &httpgrpc.HTTPRequest{
 		Method:  http.MethodPost,
-		Url:     req.Spec().Procedure,
+		Url:     url,
 		Headers: connectHeaderToHTTPGRPCHeader(h),
 	}
 	var err error
```
Comment (kolesnikovae) [inline pkg/util/connectgrpc/connectgrpc.go:145]: I don't really like it but I doubt there is a better way to ensure that the `Procedure` member of the `*connect.Request` is always present. If the request comes from the inside (i.e. not from the connect-generated handler), the caller does not have an option to specify it.

**Comment by kolesnikovae** [comment]
I also want to check if we affected by [this bug](https://github.com/pyroscope-io/flamegraph.com/issues/333)

File: pkg/util/connectgrpc/connectgrpc.go (hunk 1 above)
Comment (simonswine) [reply pkg/util/connectgrpc/connectgrpc.go:145]: Yes I think I hit that problem before, I think it is a reasonable approach.

File: pkg/util/connectgrpc/connectgrpc.go [hunk 2]
```diff
@@ -115,17 +115,31 @@ func decodeRequest[Req any](req *httpgrpc.HTTPRequest) (*connect.Request[Req], e
...
+
+func ProcedureFromContext(ctx context.Context) string {
+	s, _ := ctx.Value(connectURLCtxKey{}).(string)
+	return s
+}
+
+func encodeRequest[Req any](ctx context.Context, req *connect.Request[Req]) (*httpgrpc.HTTPRequest, error) {
+	url := req.Spec().Procedure
+	if url == "" {
+		if url = ProcedureFromContext(ctx); url == "" {
```
Comment (simonswine) [inline pkg/util/connectgrpc/connectgrpc.go:132]: Unsure which one of the two should take precedence, might be useful to override in a test using the context, but it is really arbitrary.

**Review by simonswine — APPROVED** [review]
LGTM

File: pkg/frontend/frontend_diff.go [hunk 3]
```diff
@@ -2,13 +2,52 @@ package frontend
...
+		m := phlaremodel.NewFlameGraphMerger()
+		m.MergeFlameGraph(resp.Msg.Flamegraph)
+		right = m.Tree()
+		return err
+	})
+	if err := g.Wait(); err != nil {
+		return nil, err
+	}
+
+	maxNodes := int(math.Max(c.Msg.Left.GetMaxNodes(), c.Msg.Right.GetMaxNodes()))
```
[the remark this answers is not in the document]
Comment (kolesnikovae) [reply pkg/frontend/frontend_diff.go:46]: That's a good point. Despite the fact that at the moment both left and right values source from the same HTTP query parameter, it may change in the future. I guess the right way to tackle this would be adding an explicit filed to the `DiffRequest`, because currently the semantics is pretty ambiguous. OTOH, I'm in doubts if we need to care about the limit at all – given that the trees are already truncated.
