### PR TITLE
Fix head flush orchestration

### LINKED ISSUE #2284: Investigate test timeouts
From time to time Go test CI job fails because of the timeout (10m): https://github.com/grafana/pyroscope/actions/runs/5922518424/job/16056603953

The very first time it happened on the main/next branch is: https://github.com/grafana/pyroscope/actions/runs/5888100969/job/15968636669

I think that https://github.com/grafana/pyroscope/commit/29fb2b36d1224826d8abb58e6129932865764987 could make things worse therefore the problem pops up more frequently

On the other hand, `make test` takes not longer than 100s if run locally

### PR DESCRIPTION
**Pull request by kolesnikovae**
The change makes `PhlareDB` responsible for tracking the `Head` block flush conditions.

Resolves #2284

### CODE REVIEW

File: pkg/phlaredb/phlaredb.go [hunk 1]
```diff
@@ -146,47 +157,34 @@ func (f *PhlareDB) loop() {
...
 }
 
-func (f *PhlareDB) headFlushCh() chan struct{} {
-	f.headLock.RLock()
-	defer f.headLock.RUnlock()
-	if h := f.head; h != nil {
-		return h.flushCh
+func (f *PhlareDB) maxBlockBytes() uint64 {
+	maxBlockBytes := defaultParquetConfig.MaxBlockBytes
+	if f.cfg.Parquet != nil && f.cfg.Parquet.MaxBlockBytes > maxBlockBytes {
```
Comment (simonswine) [inline pkg/phlaredb/phlaredb.go:184]: Not too sure how much sense it makes to limit the block size to the default. Maybe someone wanting to run really small clusters might benefit from setting it lower. (Currently we don't expose the limit in CLI/config at all, so this is a theoretical question)

**Review by simonswine — APPROVED** [review]
Thanks for getting to the bottom of that. 

LGTM

File: pkg/phlaredb/phlaredb.go (hunk 1 above)
Comment (kolesnikovae) [reply pkg/phlaredb/phlaredb.go]: Agreed, it makes no sense, overlooked that. Thanks for pointing out!

**Comment by kolesnikovae** [comment]
I have just realised that the block size limit is 12.8 GB, this is something we should re-asses. One one hand, it is good, because we don't want to flush symbols too often. On the other, well, someone may want to set some memory limits (although, I wouldn't rely on this given we don't have actual direct control over memory).
